### ISSUE TITLE
Conference programme

### ISSUE THREAD

**Issue by alexsavio** [euroscipy/euroscipy.github.io#14]
As an ongoing work with @alanderex we wanted to be able to export the accepted pretalx submissions from their API, convert into a [pycon-schema](https://github.com/PythonSanSebastian/pycon-schemas/tree/master/pycon_schemas/schemas), and use this schema to generate a page with the schedule.

There is probably still some refinement to do on the schema, since we haven't used it yet. 
We also need to define where do we schedule the talks and how do we automate the process of converting the pretalx output to the jsonschema format.

**Comment by pya** [comment]
Schedule page shows pretalx timetable via Javascript.
